# This file contains service configuration imports.
# To add a service configuration, create the .yml file in the /services
# directory, and add the import below.

imports: 
    - { resource: services/mailer.yml }